version: '3.7'
services:
  nginx:
    image: nginx:1.17.8
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - '.config/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - '.:/var/www/html'
    networks:
      - network
    depends_on:
      - php
  php:
    #    build: .config/php
    image: brunosilvcarv/php-oci8:8.2-fpm
    container_name: php
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - './:/var/www/html'
    networks:
      - network
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: 'teste'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./.config/postgres:/docker-entrypoint-initdb.d/
      - ./.config/postgres/data:/var/lib/postgresql/data
    networks:
      - network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "elton@email.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - network
networks:
  network: